### PR TITLE
fix array keys

### PR DESCRIPTION
**Pull request by Quexer69**
for FA::getConstants()

### CODE REVIEW

**Comment by Quexer69** [comment]
hehe ok, probably I missunderstand you... what do you mean with *replace the html code into FA::icon...*


Thats clear -> *but the array key is simply wrong, generates i.e. fahome instead of fa fa-home*

**Comment by rmrevin** [comment]
Your fix is clear. I suggest this construction
```php
? '<i class="' . static::$cssPrefix . ' ' . static::$cssPrefix . '-' . $constant . '"></i>&nbsp;&nbsp;' . $constant
```
is replaced by a call to 
```php
? FA::icon($constant) . '&nbsp;&nbsp;' . $constant
```

**Comment by rmrevin** [comment]
Merged. Thanks. I implemented my idea https://github.com/rmrevin/yii2-fontawesome/blob/master/FA.php#L29

**Comment by Quexer69** [comment]
great thx....

**Pull request merged**
